- name: pylinter
  uses: programmingwithalex/pylinter@v1.4.3

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: programmingwithalex/pylinter@v1.4.3
